name: Nuke CICD Pipeline
on:
  push:
    branches:
    - prerelease
    - master
    tags:
    - bump-*
  pull_request:
    branches:
    - '**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  PRE_SETUP:
    name: Pre Setup
    runs-on:
      labels: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
        submodules: recursive
        persist-credentials: true
    - id: NUKE_RUN
      name: Run Nuke PipelinePreSetup
      run: chmod +x ./build.sh && ./build.sh PipelinePreSetup
    timeout-minutes: 30
    outputs:
      NUKE_PRE_SETUP: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP }}
      NUKE_PRE_SETUP_OUTPUT_TEST_MATRIX: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_OUTPUT_TEST_MATRIX }}
      NUKE_PRE_SETUP_OUTPUT_BUILD_MATRIX: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_OUTPUT_BUILD_MATRIX }}
      NUKE_PRE_SETUP_OUTPUT_PUBLISH_MATRIX: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_OUTPUT_PUBLISH_MATRIX }}
      NUKE_PRE_SETUP_ABSOLUTEPATHHELPERSBUILD_CONDITION: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_ABSOLUTEPATHHELPERSBUILD_CONDITION }}
      NUKE_PRE_SETUP_ABSOLUTEPATHHELPERSBUILD_RUNS_ON: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_ABSOLUTEPATHHELPERSBUILD_RUNS_ON }}
      NUKE_PRE_SETUP_ABSOLUTEPATHHELPERSBUILD_RUN_SCRIPT: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_ABSOLUTEPATHHELPERSBUILD_RUN_SCRIPT }}
      NUKE_PRE_SETUP_ABSOLUTEPATHHELPERSBUILD_CACHE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_ABSOLUTEPATHHELPERSBUILD_CACHE_KEY }}
      NUKE_PRE_SETUP_ABSOLUTEPATHHELPERSBUILD_CACHE_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_ABSOLUTEPATHHELPERSBUILD_CACHE_RESTORE_KEY }}
      NUKE_PRE_SETUP_ABSOLUTEPATHHELPERSBUILD_CACHE_MAIN_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_ABSOLUTEPATHHELPERSBUILD_CACHE_MAIN_RESTORE_KEY }}
      NUKE_PRE_SETUP_ABSOLUTEPATHHELPERSBUILD_CHECKOUT_FETCH_DEPTH: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_ABSOLUTEPATHHELPERSBUILD_CHECKOUT_FETCH_DEPTH }}
      NUKE_PRE_SETUP_ABSOLUTEPATHHELPERSBUILD_CHECKOUT_FETCH_TAGS: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_ABSOLUTEPATHHELPERSBUILD_CHECKOUT_FETCH_TAGS }}
      NUKE_PRE_SETUP_ABSOLUTEPATHHELPERSBUILD_CHECKOUT_SUBMODULES: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_ABSOLUTEPATHHELPERSBUILD_CHECKOUT_SUBMODULES }}
      NUKE_PRE_SETUP_TEST_LINUX_CONDITION: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_TEST_LINUX_CONDITION }}
      NUKE_PRE_SETUP_TEST_LINUX_RUNS_ON: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_TEST_LINUX_RUNS_ON }}
      NUKE_PRE_SETUP_TEST_LINUX_RUN_SCRIPT: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_TEST_LINUX_RUN_SCRIPT }}
      NUKE_PRE_SETUP_TEST_LINUX_CACHE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_TEST_LINUX_CACHE_KEY }}
      NUKE_PRE_SETUP_TEST_LINUX_CACHE_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_TEST_LINUX_CACHE_RESTORE_KEY }}
      NUKE_PRE_SETUP_TEST_LINUX_CACHE_MAIN_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_TEST_LINUX_CACHE_MAIN_RESTORE_KEY }}
      NUKE_PRE_SETUP_TEST_LINUX_CHECKOUT_FETCH_DEPTH: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_TEST_LINUX_CHECKOUT_FETCH_DEPTH }}
      NUKE_PRE_SETUP_TEST_LINUX_CHECKOUT_FETCH_TAGS: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_TEST_LINUX_CHECKOUT_FETCH_TAGS }}
      NUKE_PRE_SETUP_TEST_LINUX_CHECKOUT_SUBMODULES: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_TEST_LINUX_CHECKOUT_SUBMODULES }}
      NUKE_PRE_SETUP_TEST_WINDOWS_CONDITION: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_TEST_WINDOWS_CONDITION }}
      NUKE_PRE_SETUP_TEST_WINDOWS_RUNS_ON: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_TEST_WINDOWS_RUNS_ON }}
      NUKE_PRE_SETUP_TEST_WINDOWS_RUN_SCRIPT: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_TEST_WINDOWS_RUN_SCRIPT }}
      NUKE_PRE_SETUP_TEST_WINDOWS_CACHE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_TEST_WINDOWS_CACHE_KEY }}
      NUKE_PRE_SETUP_TEST_WINDOWS_CACHE_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_TEST_WINDOWS_CACHE_RESTORE_KEY }}
      NUKE_PRE_SETUP_TEST_WINDOWS_CACHE_MAIN_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_TEST_WINDOWS_CACHE_MAIN_RESTORE_KEY }}
      NUKE_PRE_SETUP_TEST_WINDOWS_CHECKOUT_FETCH_DEPTH: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_TEST_WINDOWS_CHECKOUT_FETCH_DEPTH }}
      NUKE_PRE_SETUP_TEST_WINDOWS_CHECKOUT_FETCH_TAGS: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_TEST_WINDOWS_CHECKOUT_FETCH_TAGS }}
      NUKE_PRE_SETUP_TEST_WINDOWS_CHECKOUT_SUBMODULES: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_TEST_WINDOWS_CHECKOUT_SUBMODULES }}
      NUKE_PRE_SETUP_ABSOLUTEPATHHELPERSPUBLISH_CONDITION: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_ABSOLUTEPATHHELPERSPUBLISH_CONDITION }}
      NUKE_PRE_SETUP_ABSOLUTEPATHHELPERSPUBLISH_RUNS_ON: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_ABSOLUTEPATHHELPERSPUBLISH_RUNS_ON }}
      NUKE_PRE_SETUP_ABSOLUTEPATHHELPERSPUBLISH_RUN_SCRIPT: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_ABSOLUTEPATHHELPERSPUBLISH_RUN_SCRIPT }}
      NUKE_PRE_SETUP_ABSOLUTEPATHHELPERSPUBLISH_CACHE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_ABSOLUTEPATHHELPERSPUBLISH_CACHE_KEY }}
      NUKE_PRE_SETUP_ABSOLUTEPATHHELPERSPUBLISH_CACHE_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_ABSOLUTEPATHHELPERSPUBLISH_CACHE_RESTORE_KEY }}
      NUKE_PRE_SETUP_ABSOLUTEPATHHELPERSPUBLISH_CACHE_MAIN_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_ABSOLUTEPATHHELPERSPUBLISH_CACHE_MAIN_RESTORE_KEY }}
      NUKE_PRE_SETUP_ABSOLUTEPATHHELPERSPUBLISH_CHECKOUT_FETCH_DEPTH: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_ABSOLUTEPATHHELPERSPUBLISH_CHECKOUT_FETCH_DEPTH }}
      NUKE_PRE_SETUP_ABSOLUTEPATHHELPERSPUBLISH_CHECKOUT_FETCH_TAGS: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_ABSOLUTEPATHHELPERSPUBLISH_CHECKOUT_FETCH_TAGS }}
      NUKE_PRE_SETUP_ABSOLUTEPATHHELPERSPUBLISH_CHECKOUT_SUBMODULES: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_ABSOLUTEPATHHELPERSPUBLISH_CHECKOUT_SUBMODULES }}
  ABSOLUTEPATHHELPERSBUILD:
    name: Build - absolute_path_helpers (AbsolutePathHelpersBuild)
    runs-on: ${{ fromJson(needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_ABSOLUTEPATHHELPERSBUILD_RUNS_ON) }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_ABSOLUTEPATHHELPERSBUILD_CHECKOUT_FETCH_DEPTH }}
        fetch-tags: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_ABSOLUTEPATHHELPERSBUILD_CHECKOUT_FETCH_TAGS }}
        submodules: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_ABSOLUTEPATHHELPERSBUILD_CHECKOUT_SUBMODULES }}
        persist-credentials: true
    - name: Download absolute_path_helpers pre_test artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./.nuke/temp/artifacts-download
        pattern: pre_test___absolute_path_helpers___*
    - name: Cache Run
      uses: actions/cache@v4
      with:
        path: ./.nuke/temp/cache
        key: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_ABSOLUTEPATHHELPERSBUILD_CACHE_KEY }}
        restore-keys: |-
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_ABSOLUTEPATHHELPERSBUILD_CACHE_RESTORE_KEY }}
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_ABSOLUTEPATHHELPERSBUILD_CACHE_MAIN_RESTORE_KEY }}
    - id: NUKE_RUN
      name: Run Nuke AbsolutePathHelpersBuild
      run: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_ABSOLUTEPATHHELPERSBUILD_RUN_SCRIPT }} Run --args "AbsolutePathHelpersBuild"
    - name: Upload absolute_path_helpers build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build___absolute_path_helpers___ABSOLUTEPATHHELPERSBUILD
        path: ./.nuke/temp/artifacts-upload/absolute_path_helpers/*
        if-no-files-found: error
        retention-days: 1
    - name: Upload common build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build___$common___ABSOLUTEPATHHELPERSBUILD
        path: ./.nuke/temp/artifacts-upload/$common/*
        if-no-files-found: error
        retention-days: 1
    needs:
    - PRE_SETUP
    if: "! failure() && ! cancelled() && needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_ABSOLUTEPATHHELPERSBUILD_CONDITION == 'true'"
    env:
      NUKE_PRE_SETUP: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP }}
  TEST_LINUX:
    name: Test - absolute_path_helpers (TEST_LINUX)
    runs-on: ${{ fromJson(needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_TEST_LINUX_RUNS_ON) }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_TEST_LINUX_CHECKOUT_FETCH_DEPTH }}
        fetch-tags: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_TEST_LINUX_CHECKOUT_FETCH_TAGS }}
        submodules: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_TEST_LINUX_CHECKOUT_SUBMODULES }}
        persist-credentials: true
    - name: Download absolute_path_helpers pre_test artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./.nuke/temp/artifacts-download
        pattern: pre_test___absolute_path_helpers___*
    - name: Download absolute_path_helpers build artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./.nuke/temp/artifacts-download
        pattern: build___absolute_path_helpers___*
    - name: Cache Run
      uses: actions/cache@v4
      with:
        path: ./.nuke/temp/cache
        key: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_TEST_LINUX_CACHE_KEY }}
        restore-keys: |-
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_TEST_LINUX_CACHE_RESTORE_KEY }}
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_TEST_LINUX_CACHE_MAIN_RESTORE_KEY }}
    - id: NUKE_RUN
      name: Run Nuke TEST_LINUX
      run: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_TEST_LINUX_RUN_SCRIPT }} Run --args "TEST_LINUX"
    - name: Upload absolute_path_helpers post_test artifacts
      uses: actions/upload-artifact@v4
      with:
        name: post_test___absolute_path_helpers___TEST_LINUX
        path: ./.nuke/temp/artifacts-upload/absolute_path_helpers/*
        if-no-files-found: error
        retention-days: 1
    - name: Upload common post_test artifacts
      uses: actions/upload-artifact@v4
      with:
        name: post_test___$common___TEST_LINUX
        path: ./.nuke/temp/artifacts-upload/$common/*
        if-no-files-found: error
        retention-days: 1
    needs:
    - PRE_SETUP
    - ABSOLUTEPATHHELPERSBUILD
    if: "! failure() && ! cancelled() && needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_TEST_LINUX_CONDITION == 'true' && needs.ABSOLUTEPATHHELPERSBUILD.result == 'success'"
    env:
      NUKE_PRE_SETUP: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP }}
  TEST_WINDOWS:
    name: Test - absolute_path_helpers (TEST_WINDOWS)
    runs-on: ${{ fromJson(needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_TEST_WINDOWS_RUNS_ON) }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_TEST_WINDOWS_CHECKOUT_FETCH_DEPTH }}
        fetch-tags: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_TEST_WINDOWS_CHECKOUT_FETCH_TAGS }}
        submodules: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_TEST_WINDOWS_CHECKOUT_SUBMODULES }}
        persist-credentials: true
    - name: Download absolute_path_helpers pre_test artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./.nuke/temp/artifacts-download
        pattern: pre_test___absolute_path_helpers___*
    - name: Download absolute_path_helpers build artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./.nuke/temp/artifacts-download
        pattern: build___absolute_path_helpers___*
    - name: Cache Run
      uses: actions/cache@v4
      with:
        path: ./.nuke/temp/cache
        key: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_TEST_WINDOWS_CACHE_KEY }}
        restore-keys: |-
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_TEST_WINDOWS_CACHE_RESTORE_KEY }}
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_TEST_WINDOWS_CACHE_MAIN_RESTORE_KEY }}
    - id: NUKE_RUN
      name: Run Nuke TEST_WINDOWS
      run: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_TEST_WINDOWS_RUN_SCRIPT }} Run --args "TEST_WINDOWS"
    - name: Upload absolute_path_helpers post_test artifacts
      uses: actions/upload-artifact@v4
      with:
        name: post_test___absolute_path_helpers___TEST_WINDOWS
        path: ./.nuke/temp/artifacts-upload/absolute_path_helpers/*
        if-no-files-found: error
        retention-days: 1
    - name: Upload common post_test artifacts
      uses: actions/upload-artifact@v4
      with:
        name: post_test___$common___TEST_WINDOWS
        path: ./.nuke/temp/artifacts-upload/$common/*
        if-no-files-found: error
        retention-days: 1
    needs:
    - PRE_SETUP
    - ABSOLUTEPATHHELPERSBUILD
    if: "! failure() && ! cancelled() && needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_TEST_WINDOWS_CONDITION == 'true' && needs.ABSOLUTEPATHHELPERSBUILD.result == 'success'"
    env:
      NUKE_PRE_SETUP: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP }}
  ABSOLUTEPATHHELPERSPUBLISH:
    name: Publish - absolute_path_helpers (AbsolutePathHelpersPublish)
    runs-on: ${{ fromJson(needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_ABSOLUTEPATHHELPERSPUBLISH_RUNS_ON) }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_ABSOLUTEPATHHELPERSPUBLISH_CHECKOUT_FETCH_DEPTH }}
        fetch-tags: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_ABSOLUTEPATHHELPERSPUBLISH_CHECKOUT_FETCH_TAGS }}
        submodules: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_ABSOLUTEPATHHELPERSPUBLISH_CHECKOUT_SUBMODULES }}
        persist-credentials: true
    - name: Download absolute_path_helpers pre_test artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./.nuke/temp/artifacts-download
        pattern: pre_test___absolute_path_helpers___*
    - name: Download absolute_path_helpers build artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./.nuke/temp/artifacts-download
        pattern: build___absolute_path_helpers___*
    - name: Download absolute_path_helpers post_test artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./.nuke/temp/artifacts-download
        pattern: post_test___absolute_path_helpers___*
    - name: Cache Run
      uses: actions/cache@v4
      with:
        path: ./.nuke/temp/cache
        key: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_ABSOLUTEPATHHELPERSPUBLISH_CACHE_KEY }}
        restore-keys: |-
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_ABSOLUTEPATHHELPERSPUBLISH_CACHE_RESTORE_KEY }}
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_ABSOLUTEPATHHELPERSPUBLISH_CACHE_MAIN_RESTORE_KEY }}
    - id: NUKE_RUN
      name: Run Nuke AbsolutePathHelpersPublish
      run: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_ABSOLUTEPATHHELPERSPUBLISH_RUN_SCRIPT }} Run --args "AbsolutePathHelpersPublish"
    - name: Upload common publish artifacts
      uses: actions/upload-artifact@v4
      with:
        name: publish___$common___ABSOLUTEPATHHELPERSPUBLISH
        path: ./.nuke/temp/artifacts-upload/$common/*
        if-no-files-found: error
        retention-days: 1
    needs:
    - PRE_SETUP
    - ABSOLUTEPATHHELPERSBUILD
    - TEST_LINUX
    - TEST_WINDOWS
    if: "! failure() && ! cancelled() && needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_ABSOLUTEPATHHELPERSPUBLISH_CONDITION == 'true' && needs.ABSOLUTEPATHHELPERSBUILD.result == 'success' && needs.TEST_LINUX.result == 'success' && needs.TEST_WINDOWS.result == 'success'"
    env:
      NUKE_PRE_SETUP: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP }}
  POST_SETUP:
    name: Post Setup
    runs-on:
      labels: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
        submodules: recursive
        persist-credentials: true
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./.nuke/temp/artifacts-download
        pattern: '*___*'
    - name: Run Nuke PipelinePostSetup
      run: chmod +x ./build.sh && ./build.sh PipelinePostSetup
    needs:
    - PRE_SETUP
    - ABSOLUTEPATHHELPERSBUILD
    - TEST_LINUX
    - TEST_WINDOWS
    - ABSOLUTEPATHHELPERSPUBLISH
    if: success() || failure() || always()
    timeout-minutes: 30
    env:
      NUKE_PRE_SETUP: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP }}
      NUKE_RUN_RESULT_GITHUB_ABSOLUTEPATHHELPERSBUILD: ${{ needs.ABSOLUTEPATHHELPERSBUILD.result }}
      NUKE_RUN_RESULT_GITHUB_TEST_LINUX: ${{ needs.TEST_LINUX.result }}
      NUKE_RUN_RESULT_GITHUB_TEST_WINDOWS: ${{ needs.TEST_WINDOWS.result }}
      NUKE_RUN_RESULT_GITHUB_ABSOLUTEPATHHELPERSPUBLISH: ${{ needs.ABSOLUTEPATHHELPERSPUBLISH.result }}
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NUKE_NUGET_AUTH_TOKEN: ${{ secrets.NUGET_AUTH_TOKEN }}
  NUKE_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
